name: CraftingPlus
main: xyz.acrylicstyle.crafting.Crafting
version: 1.0-SNAPSHOT
api-version: "1.15"
commands:
  open4x4:
    aliases: ["4x4"]
  open5x5:
    aliases: ["5x5"]
  recipes4x4:
    description: "Shows recipe list of 4x4 recipes."
  recipes5x5:
    description: "Shows recipe list of 5x5 recipes."
  reloadrecipes:
    aliases: ["reload_recipes"]
  give5x5:
    aliases: ["5x5give"]